---
title: "Projects"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r metathis, message=FALSE, warning=FALSE, include=FALSE}
library(metathis)

meta() %>%
  meta_description(
    "A selection of Duncan Gates's projects"
  ) %>%
  meta_name("github-repo" = "dungates/duncangates-distill") %>%
  meta_viewport() %>%
  meta_social(
    title = "DUNCAN GATES: Projects",
    url = "https://ellakaye.rbind.io/projects",
    image = "https://ellakaye.rbind.io/images/logo-white-background.png",
    image_alt = "A logo made from Duncan Gates's name - first name on top of last name in black capital letters, separated by a horizontal bright pink line",
    og_type = "website",
    og_author = c("Duncan Gates"),
    twitter_card_type = "summary",
    twitter_creator = "@gates_duncan"
  )
```


```{r, include=FALSE}
library(htmltools)
source("R/create_proj_card.R")
```

```{r}
create_proj_card(
  img_src = "images/projects/distilltools-hex.png",
  url = "https://ellakaye.github.io/distilltools/",
  title = "{distilltools}",
  text = "The {distilltools} R package is a collection of tools to support the creation and styling of content on blogs/wesbites made with the {distill} package.",
  text2 = NULL
)

create_proj_card(
  img_src = "images/projects/TidyTuesday.png",
  url = "https://github.com/dungates/TidyTuesday",
  title = "TidyTuesday",
  text = "My (infrequent) contributions to #TidyTuesday",
  text2 = NULL
)

create_proj_card(
  img_src = "images/projects/BradleyTerryScalable-hex.png",
  url = "https://ellakaye.github.io/BradleyTerryScalable/",
  title = "{BradleyTerryScalable}",
  text = "An R pacakge for fitting the Bradley-Terry model to potentially large and sparse networks for paired comparison data.",
  text2 = NULL
)

create_proj_card(
  img_src = "images/projects/EMK-hex.png",
  url = "https://github.com/dungates/EMK",
  title = "{EMK}",
  text = "A personal R package of a collection of miscellaneous functions I find useful.",
  text2 = NULL
)
```

